### ISSUE TITLE
Add Compatibility with GNOME 42.9 (Latest Ubuntu LTS)

### ISSUE THREAD

**Issue by CarJem** [Vishram1123/gjs-osk#16] opened 2023-09-10 18:58 UTC
I did a quick look at what would be required to do this and it turns out the only thing that would be needed is a simple change to the signals import

```js
const Config = imports.misc.config;
const [major, minor] = Config.PACKAGE_VERSION.split('.').map(s => Number(s));
const Signals = major === 42 && minor <= 9 ? imports.signals : imports.misc.signals;
```
And off course updating the metadata to accept said version. If you approve I can make a PR to do this easily

And before anyone says "just update to GNOME 43", newer gnome's IMO have stability issues and I don't foresee Ubuntu changing versions anytime soon for stability reasons.

**Comment by CarJem** [comment] 2023-09-11 12:25
I originally closed this because I made this statement on the store version available, and not the source. 

that said I will reopen this as I do have big interest in implementing this, since 42.9 will remain on LTS til at least April 2024 likely.

if I get to go ahead implement this compatibility, I shall dispatch a PR of my edits

**Comment by yfreund** [comment] 2023-09-13 01:20
I am not the maintainer of this package, so it's not up to me to decide whether this change is to be implemented, but I have a few questions (based on my contributions to other extensions in the past):
* Why are you specifying/relying on the version instead of checking whether the import itself exists? That would greatly simplify your code.
* You're checking for a minor version. This seems unnecessary - is this change not needed for GNOME 42.10, which was released in March, and might find its way into a dot release of Ubuntu 22.04 some day (or perhaps be used on other distros)? What about potential future versions of GNOME 42?
* Have you tried to apply these changes locally, to see if the extension works on your machine? Have you tested all features and preferences, to make sure that things such as the version of `libadwaita` in GNOME 42 are completely compatible with this extension?

For the record - I do *not* think that you should upgrade to GNOME 43 just to use this extension, and I understand that the current situation is inconvenient to you, but I'm sure that the maintainer of this extension didn't make the decision to support this extension from a certain version arbitrarily. Testing and ensuring compatibility for all features takes time and effort, and seeing how GNOME 45 required a rewrite of all extensions, supporting older version is going to get more and more tedious.

I hope you find this comment useful, and that it finds you well.

**Comment by CarJem** [comment] 2023-09-13 17:52
> I am not the maintainer of this package, so it's not up to me to decide whether this change is to be implemented, but I have a few questions (based on my contributions to other extensions in the past):
> * Why are you specifying/relying on the version instead of checking whether the import itself exists? That would greatly simplify your code.
> * You're checking for a minor version. This seems unnecessary - is this change not needed for GNOME 42.10, which was released in March, and might find its way into a dot release of Ubuntu 22.04 some day (or perhaps be used on other distros)? What about potential (unofficial) future versions of GNOME 42?
> * Have you tried to apply these changes locally, to see if the extension works on your machine? Have you tested all features and preferences, to make sure that things such as the version of `libadwaita` in GNOME 42 are completely compatible with this extension?
> 
> For the record - I do *not* think that you should upgrade to GNOME 43 just to use this extension, and I understand that the current situation is inconvenient to you, but I'm sure that the maintainer of this extension didn't make the decision to support this extension from a certain version arbitrarily. Testing and ensuring compatibility for all features takes time and effort, and seeing how GNOME 45 required a rewrite of all extensions, supporting older version is going to get more and more tedious.
> 
> I hope you find this comment useful, and that it finds you well.

1. I'm kind of new to this, but I can always make improvements
2. I'm only able to currently test with my Ubuntu LTS which is at 42.9
3. I made some edits to get the code base working and I do have a working copy on my end now that I use on a regular basis as my on-screen keyboard

I could just fork this I know, but if I do that I would miss out on potential improvements to the base code

**Comment by yfreund** [comment] 2023-09-13 19:26
> 1. I'm kind of new to this, but I can always make improvements

Good - the point of my questions was to determine why you've made certain decisions and help you make improvements. I find it more helpful to point people in the right direction than rewriting their code, or do the research for them - it presents a good opportunity for growth.

> 2. I'm only able to currently test with my Ubuntu LTS which is at 42.9

You can verify whether this change is needed for other versions of GNOME 42 by looking at the GNOME source code and Changelog, and noting what has (and hasn't) changed. Currently, your above code does not apply to any versions above 42.9, and all 42 versions below it - I don't think it would make sense to supports GNOME 42 up to a certain version, and all GNOME versions above, or potentially have things break on older versions of GNOME 42 (the latter is somewhat less likely but still possible). Do you agree?

A much better and cleaner solution would be to rely on something other than the version number for this case - I suggest you do some research on how to check whether a module exists.

(BTW - Ubuntu 22.04 LTS was released with GNOME 42.0 , and the updates to higher versions became available over `jammy-updates`, so there are even users of that specific Ubuntu version which are using different GNOME 42 versions, due to other constraints or just laziness when it comes to system updates 😅)

> 3. I made some edits to get the code base working and I do have a working copy on my end now that I use on a regular basis as my on-screen keyboard

Ok, I'm personally very happy to hear that - I can't comment on any other changes without seeing them (if I understand you correctly, you did have to make a few more edits), but you haven't specified whether you have tested all features, or just the core functionality/things you are personally using.
 
> I could just fork this I know, but if I do that I would miss out on potential improvements to the base code

Yes, you _could_ fork it if you wanted, and lose the ability to get official updates to this extension in the future. I agree with you that this isn't a good idea, unless the maintainer rejects the idea of supporting older versions of GNOME.
I think you're doing the right things by asking - I was mostly pointing out what would be involved from the maintainer's side, and that adding support for older versions should not be taken for granted, even if it seems like an arbitrary change to you.

The other question would be how much support older versions of GNOME will get for this extension once GNOME 45 is released, since the maintainer would have to support two separate versions due to the (very) breaking changes in that GNOME version.

> additionally there is this bug that inhibits my ability to use newer versions of GNOME, it may be fixed soon, but I don't know (I am using a 2 in 1 with a tablet experience when I wish to)

As I mentioned before, there's no expectation for you to upgrade your GNOME version just in order to use this extension. There's no need to defend your position for using this GNOME version, and it's taking focus away from other topics.

If the maintainer decides to support this change - great!  If not, you seem to have a version that works until you decide to (and can) upgrade. There are also other alternatives you could use, though I'm also very fond of this OSK in particular.

**Comment by CarJem** [comment] 2023-09-14 16:27
I'll see to it that at the very least I compare GNOME 42.0 and validate compatibility, additionally there are some observations I have made with my edits:

- the unpublished offical indicator changes do require extended backwards compatibility, as they did not exist until 43. I have implemented this the best I could.

- the keyboard does not properly work with mouse inputs in X11, and things like click  events can just go straight through the window. touch is fine though, and none of these issues persist in Wayland. not sure if this is an existing bug or a lack of backporting on my part 

- bug or not, I did decide to change the indicator characters for moving and closing the keyboard, since they do not exist in most fonts as unicode symbols (since this is opinionated I can easily and will revert this if needed, and I have no idea if this is a bug)

**Comment by in4matix** [comment] 2023-09-26 09:44
> I did a quick look at what would be required to do this and it turns out the only thing that would be needed is a simple change to the signals import
> 
> ```js
> const Config = imports.misc.config;
> const [major, minor] = Config.PACKAGE_VERSION.split('.').map(s => Number(s));
> const Signals = major === 42 && minor <= 9 ? imports.signals : imports.misc.signals;
> ```
> 
> And off course updating the metadata to accept said version. If you approve I can make a PR to do this easily
> 
> And before anyone says "just update to GNOME 43", newer gnome's IMO have stability issues and I don't foresee Ubuntu changing versions anytime soon for stability reasons.

I totally agree. The issues with newer Gnome is very real (running Ubuntu 23.10 Beta & Fedora 39 Beta). Ubuntu 22.04 LTS is stable, lightening fast, and has very little issues, even while running 80+ extensions... I personally hope Ubuntu stays on 42.9 until Gnome 45 has been fixed and streamlined, and then Ubuntu can jump straight to Gnome 45, and completely bypass Gnome 43-44 altogether.

**Comment by Vishram1123** [comment] 2023-09-27 18:05
Just fixed this compatibility with Gnome 42, and committed to [pre-45](https://github.com/Vishram1123/gjs-osk/tree/pre-45) ([this commit](https://github.com/Vishram1123/gjs-osk/commit/e2342ed78f7d32a181c37b6a86b00fba6d8c67d6)), so if you clone to pre-45, you can get the working version of your keyboard for Gnome 42. Thank you for the code above, and sorry I couldn't respond to this for a while.

**Closed by Vishram1123** 2023-09-27 18:05 UTC

**Comment by in4matix** [comment] 2023-09-27 18:54
Awesomeness, thank you !!

**Comment by in4matix** [comment] 2023-09-27 21:08
I can confirm that it is working flawlessly on Ubuntu 23.04.3 (Gnome 42.9)

![Screenshot from 2023-09-27 23-03-42](https://github.com/Vishram1123/gjs-osk/assets/62904593/6fa1349b-bbfb-4b14-b1bd-7e7b2432b319)
