### ISSUE TITLE
Keyboard error after unlock

### ISSUE THREAD

**Issue by yukina3230** [Vishram1123/gjs-osk#9] opened 2023-05-15 19:17 UTC
I set the screen to turn off every 10 minutes, and when I unlock, I got this layout issue.

The keyboard cannot be used and the tray icon disappeared
![Screenshot from 2023-05-16 01-55-18](https://github.com/Vishram1123/gjs-osk/assets/75545944/54fd9b4a-c14f-4ac9-9d50-f9be6d667b01)

And in the Extension Manager shows this error
![Screenshot from 2023-05-16 01-56-29](https://github.com/Vishram1123/gjs-osk/assets/75545944/a28bf982-267d-422c-9296-568030c3b4ee)

**Comment by Vishram1123** [comment] 2023-05-17 21:15
It appears that the KeyboardManager isn't initialized by the time that the extension is ready to reactivate after login. I will add a timeout to the refresh and initialization functions to allow time for KeyboardManager to reinitialize.

**Comment by Vishram1123** [comment] 2023-05-21 00:17
I should have fixed the issue with [this commit](https://github.com/Vishram1123/gjs-osk/commit/b9f9d430e206a21cb75133f35c2db08f5c3effa8). Check if this works

**Comment by yukina3230** [comment] 2023-05-21 14:09
I tested it, no more layout bug after unlock but keyboard doesn't show when clicking on the icon

**Comment by yukina3230** [comment] 2023-05-22 17:33
I tried to reproduce the error, it seems to be due to my keyboard language, when I set it to English, the keyboard still works, but when I switch to Vietnamese, it doesn't show up anymore.

https://github.com/Vishram1123/gjs-osk/assets/75545944/e8b084a3-faed-4959-9dd3-a35336f5f747

**Comment by Vishram1123** [comment] 2023-05-23 16:04
Could you try [this commit](https://github.com/Vishram1123/gjs-osk/commit/4ac0603d105c841c580314ceea4d2e2afa2b608c)?

**Comment by yukina3230** [comment] 2023-05-23 16:46
Hi, I tried your commit, after unlock, the keyboard appears on the corner like this.

![Screenshot from 2023-05-23 23-40-55](https://github.com/Vishram1123/gjs-osk/assets/75545944/b453af76-64ad-438b-8ae3-d0b1d72a14a5)

**Comment by Vishram1123** [comment] 2023-05-23 19:36
Which version of GNOME are you on?

**Comment by yukina3230** [comment] 2023-05-23 20:03
Gnome 44.1, here is other info

![Screenshot from 2023-05-24 03-01-45](https://github.com/Vishram1123/gjs-osk/assets/75545944/45d6865a-1a65-419d-91b0-20d8668d650f)

**Comment by Vishram1123** [comment] 2023-05-23 20:11
I just made a commit, try that?

**Comment by yukina3230** [comment] 2023-05-23 21:14
Hi, I tried your commit, still got the same issue.

**Comment by Vishram1123** [comment] 2023-05-23 21:20
I tried making another change in the latest commit, to make it wait until KeyboardManager is initialized. Could you check now?

**Comment by yukina3230** [comment] 2023-05-24 04:48
I tried it, the keyboard doesn't show in the corner anymore but it still doesn't work with Vietnamese.

**Comment by Vishram1123** [comment] 2023-05-24 12:20
If it switches to US layout upon opening, then back to a Vietnamese layout after closing, that is the intended behavior. I haven't implemented the Vietnamese layout yet, but I will do so soon.

**Closed** 2023-05-25 00:52 UTC
Labels: bug
