### ISSUE TITLE
Can't type into system modal dialogs

### ISSUE THREAD

**Issue by kdolum** [Vishram1123/gjs-osk#47] opened 2024-05-14 20:33 UTC
I hope I'm using the terminology correctly.  When I connect to a network that requires a password, or if I try to use an ssh key that is locked, I get a pop-up that takes over the whole screen to prompt for the password.  Then I can't touch anywhere, including the GJS OSK keys, so I can't type the password.  However, if I disable GJS OSK and turn on the default OSK, it appears in this situation and I can use it to type the password.  Is there some way that GJS could work in the situation also? 

I'm using Autorelease 3708d07 in Ubuntu 24.04 LTS on a Surface Pro 6.

Thanks.

**Comment by Vishram1123** [comment] 2024-05-23 04:45
Sorry for the late response, but this is a duplicate of #11. I think I will try to make it such that it will open the default onscreen keyboard when a modal is present

**Closed by Vishram1123** 2024-05-23 04:45 UTC

**Comment by Vishram1123** [comment] 2024-06-08 08:55
This should be fixed now, the only problem is that the keyboard either has to be already open when the modal dialog is opened, or auto-opening has to be enabled.

**Comment by Vishram1123** [comment] 2024-06-08 09:16
Fixed in commit 88e183d, where tapping on an input field while a dialog is opened will open the keyboard modal.
